commitizen:
  name: cz_customize
  tag_format: v$version
  version: 0.1.0
  customize:
    change_type_order: ["BREAKING CHANGE", "feat", "build", "fix", "perf", "refactor", "style"]
    commit_parser: "^(?P<change_type>feature|feat|bug fix|bug|fix|perf|build|ci|docs|refactor):\\s(?P<message>.*)?"
    changelog_pattern: "^(feature|feat|bugfix|bug|fix|perf|build|ci|docs|refactor|perf)?(!)?"
    change_type_map:
      feat: Features
      feature: Features
      bug fix: Fixes
      bugfix: Fixes
      bug: Fixes
      fix: Fixes
      ci: CI
      build: Build
      docs: Documentation
      refactor: Refactor
      perf: Performance
      style: Code style